title: Kerry Yu
logo: /assets/img/Kerry 016.png
description: Recent UC Santa Barbara graduate with a Bachelors of Science (B.S.) in Statistics and Data Science. 
theme: jekyll-theme-minimal
linkedin: https://www.linkedin.com/in/kerry-yu-849129369/
